### ISSUE TITLE
Image is not uploading

### ISSUE THREAD

**Issue by samirspatel** [phptuts/symfonystarter#2]
This one does not upload for some reason 

![colorful-chameleon](https://user-images.githubusercontent.com/22302566/28326086-629362a8-6ba5-11e7-8364-26158ff30428.jpg)

**Comment by phptuts** [comment]
@samirspatel 
Fixed issues it was a badly spelled mime type.  Should be able to upload jpegs now.  Thanks for the bug report.

**Comment by phptuts** [comment]
Not sure if I should close this.

**Comment by phptuts** [comment]
@samirspatel closing issue
